name: Terraform
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGION_DEFAULT: us-east-1

jobs:
  create_infra:
    name: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false -auto-approve
        env:
          TF_VAR_mailtrap_host: ${{ secrets.MAILTRAP_HOST }}
          TF_VAR_mailtrap_port: ${{ secrets.MAILTRAP_PORT }}
          TF_VAR_mailtrap_pass: ${{ secrets.MAILTRAP_PASS }}
          TF_VAR_mailtrap_user: ${{ secrets.MAILTRAP_USER }}
          TF_VAR_aws_access_key_id: ${{ secrets.ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          TF_VAR_aws_session_token: ${{ secrets.SESSION_TOKEN }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_aws_s3_bucket: ${{ vars.AWS_S3_BUCKET }}
          TF_VAR_redis_host: ${{ vars.REDIS_HOST }}
          TF_VAR_redis_port: ${{ vars.REDIS_PORT }}
          TF_VAR_sqs_files_to_process_url: ${{ vars.SQS_FILES_TO_PROCESS_URL }}
          TF_VAR_sqs_queue_url : ${{ vars.SQS_QUEUE_URL }}
          TF_VAR_sqs_notification_queue_url: ${{ vars.AWS_SQS_NOTIFICATION_QUEUE_URL }}
          TF_VAR_postgres_user: ${{ secrets.postgres_user }}
          TF_VAR_postgres_password: ${{ secrets.postgres_password }}
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
          TF_VAR_db_user: ${{ secrets.DB_USER }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_database: ${{ secrets.DB_DATABASE }}



          
